// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: example/blog.proto

package main

import (
	fmt "fmt"
	_ "github.com/cjp2600/structify/plugin/options"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

var a string = "hello"
