// Code generated by protoc-gen-go. DO NOT EDIT.
// source: plugin/options/structify.proto

package structify

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StructifyDBOptions struct {
	Provider             string   `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Url                  string   `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	UrlEnv               string   `protobuf:"bytes,3,opt,name=url_env,json=urlEnv,proto3" json:"url_env,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StructifyDBOptions) Reset()         { *m = StructifyDBOptions{} }
func (m *StructifyDBOptions) String() string { return proto.CompactTextString(m) }
func (*StructifyDBOptions) ProtoMessage()    {}
func (*StructifyDBOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_e38015b89ec607b3, []int{0}
}

func (m *StructifyDBOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StructifyDBOptions.Unmarshal(m, b)
}
func (m *StructifyDBOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StructifyDBOptions.Marshal(b, m, deterministic)
}
func (m *StructifyDBOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StructifyDBOptions.Merge(m, src)
}
func (m *StructifyDBOptions) XXX_Size() int {
	return xxx_messageInfo_StructifyDBOptions.Size(m)
}
func (m *StructifyDBOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_StructifyDBOptions.DiscardUnknown(m)
}

var xxx_messageInfo_StructifyDBOptions proto.InternalMessageInfo

func (m *StructifyDBOptions) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

func (m *StructifyDBOptions) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *StructifyDBOptions) GetUrlEnv() string {
	if m != nil {
		return m.UrlEnv
	}
	return ""
}

type StructifyMessageOptions struct {
	Table                string   `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	Comment              string   `protobuf:"bytes,2,opt,name=comment,proto3" json:"comment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StructifyMessageOptions) Reset()         { *m = StructifyMessageOptions{} }
func (m *StructifyMessageOptions) String() string { return proto.CompactTextString(m) }
func (*StructifyMessageOptions) ProtoMessage()    {}
func (*StructifyMessageOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_e38015b89ec607b3, []int{1}
}

func (m *StructifyMessageOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StructifyMessageOptions.Unmarshal(m, b)
}
func (m *StructifyMessageOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StructifyMessageOptions.Marshal(b, m, deterministic)
}
func (m *StructifyMessageOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StructifyMessageOptions.Merge(m, src)
}
func (m *StructifyMessageOptions) XXX_Size() int {
	return xxx_messageInfo_StructifyMessageOptions.Size(m)
}
func (m *StructifyMessageOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_StructifyMessageOptions.DiscardUnknown(m)
}

var xxx_messageInfo_StructifyMessageOptions proto.InternalMessageInfo

func (m *StructifyMessageOptions) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

func (m *StructifyMessageOptions) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

type StructifyFieldOptions struct {
	PrimaryKey           bool      `protobuf:"varint,1,opt,name=primary_key,json=primaryKey,proto3" json:"primary_key,omitempty"`
	AutoIncrement        bool      `protobuf:"varint,2,opt,name=auto_increment,json=autoIncrement,proto3" json:"auto_increment,omitempty"`
	Unique               bool      `protobuf:"varint,3,opt,name=unique,proto3" json:"unique,omitempty"`
	Uuid                 bool      `protobuf:"varint,4,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Index                bool      `protobuf:"varint,5,opt,name=index,proto3" json:"index,omitempty"`
	Skip                 bool      `protobuf:"varint,6,opt,name=skip,proto3" json:"skip,omitempty"`
	Nullable             bool      `protobuf:"varint,7,opt,name=nullable,proto3" json:"nullable,omitempty"`
	Default              string    `protobuf:"bytes,8,opt,name=default,proto3" json:"default,omitempty"`
	Relation             *Relation `protobuf:"bytes,9,opt,name=relation,proto3" json:"relation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *StructifyFieldOptions) Reset()         { *m = StructifyFieldOptions{} }
func (m *StructifyFieldOptions) String() string { return proto.CompactTextString(m) }
func (*StructifyFieldOptions) ProtoMessage()    {}
func (*StructifyFieldOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_e38015b89ec607b3, []int{2}
}

func (m *StructifyFieldOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StructifyFieldOptions.Unmarshal(m, b)
}
func (m *StructifyFieldOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StructifyFieldOptions.Marshal(b, m, deterministic)
}
func (m *StructifyFieldOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StructifyFieldOptions.Merge(m, src)
}
func (m *StructifyFieldOptions) XXX_Size() int {
	return xxx_messageInfo_StructifyFieldOptions.Size(m)
}
func (m *StructifyFieldOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_StructifyFieldOptions.DiscardUnknown(m)
}

var xxx_messageInfo_StructifyFieldOptions proto.InternalMessageInfo

func (m *StructifyFieldOptions) GetPrimaryKey() bool {
	if m != nil {
		return m.PrimaryKey
	}
	return false
}

func (m *StructifyFieldOptions) GetAutoIncrement() bool {
	if m != nil {
		return m.AutoIncrement
	}
	return false
}

func (m *StructifyFieldOptions) GetUnique() bool {
	if m != nil {
		return m.Unique
	}
	return false
}

func (m *StructifyFieldOptions) GetUuid() bool {
	if m != nil {
		return m.Uuid
	}
	return false
}

func (m *StructifyFieldOptions) GetIndex() bool {
	if m != nil {
		return m.Index
	}
	return false
}

func (m *StructifyFieldOptions) GetSkip() bool {
	if m != nil {
		return m.Skip
	}
	return false
}

func (m *StructifyFieldOptions) GetNullable() bool {
	if m != nil {
		return m.Nullable
	}
	return false
}

func (m *StructifyFieldOptions) GetDefault() string {
	if m != nil {
		return m.Default
	}
	return ""
}

func (m *StructifyFieldOptions) GetRelation() *Relation {
	if m != nil {
		return m.Relation
	}
	return nil
}

type Relation struct {
	Fields               []string `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
	References           []string `protobuf:"bytes,2,rep,name=references,proto3" json:"references,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Relation) Reset()         { *m = Relation{} }
func (m *Relation) String() string { return proto.CompactTextString(m) }
func (*Relation) ProtoMessage()    {}
func (*Relation) Descriptor() ([]byte, []int) {
	return fileDescriptor_e38015b89ec607b3, []int{3}
}

func (m *Relation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Relation.Unmarshal(m, b)
}
func (m *Relation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Relation.Marshal(b, m, deterministic)
}
func (m *Relation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Relation.Merge(m, src)
}
func (m *Relation) XXX_Size() int {
	return xxx_messageInfo_Relation.Size(m)
}
func (m *Relation) XXX_DiscardUnknown() {
	xxx_messageInfo_Relation.DiscardUnknown(m)
}

var xxx_messageInfo_Relation proto.InternalMessageInfo

func (m *Relation) GetFields() []string {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *Relation) GetReferences() []string {
	if m != nil {
		return m.References
	}
	return nil
}

type MethodOptions struct {
	ObjectType           string   `protobuf:"bytes,1,opt,name=object_type,json=objectType,proto3" json:"object_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MethodOptions) Reset()         { *m = MethodOptions{} }
func (m *MethodOptions) String() string { return proto.CompactTextString(m) }
func (*MethodOptions) ProtoMessage()    {}
func (*MethodOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_e38015b89ec607b3, []int{4}
}

func (m *MethodOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MethodOptions.Unmarshal(m, b)
}
func (m *MethodOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MethodOptions.Marshal(b, m, deterministic)
}
func (m *MethodOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MethodOptions.Merge(m, src)
}
func (m *MethodOptions) XXX_Size() int {
	return xxx_messageInfo_MethodOptions.Size(m)
}
func (m *MethodOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_MethodOptions.DiscardUnknown(m)
}

var xxx_messageInfo_MethodOptions proto.InternalMessageInfo

func (m *MethodOptions) GetObjectType() string {
	if m != nil {
		return m.ObjectType
	}
	return ""
}

var E_Db = &proto.ExtensionDesc{
	ExtendedType:  (*descriptorpb.FileOptions)(nil),
	ExtensionType: (*StructifyDBOptions)(nil),
	Field:         50002,
	Name:          "structify.db",
	Tag:           "bytes,50002,opt,name=db",
	Filename:      "plugin/options/structify.proto",
}

var E_Opts = &proto.ExtensionDesc{
	ExtendedType:  (*descriptorpb.MessageOptions)(nil),
	ExtensionType: (*StructifyMessageOptions)(nil),
	Field:         99432,
	Name:          "structify.opts",
	Tag:           "bytes,99432,opt,name=opts",
	Filename:      "plugin/options/structify.proto",
}

var E_Field = &proto.ExtensionDesc{
	ExtendedType:  (*descriptorpb.FieldOptions)(nil),
	ExtensionType: (*StructifyFieldOptions)(nil),
	Field:         99432,
	Name:          "structify.field",
	Tag:           "bytes,99432,opt,name=field",
	Filename:      "plugin/options/structify.proto",
}

var E_Method = &proto.ExtensionDesc{
	ExtendedType:  (*descriptorpb.MethodOptions)(nil),
	ExtensionType: (*MethodOptions)(nil),
	Field:         99432,
	Name:          "structify.method",
	Tag:           "bytes,99432,opt,name=method",
	Filename:      "plugin/options/structify.proto",
}

func init() {
	proto.RegisterType((*StructifyDBOptions)(nil), "structify.StructifyDBOptions")
	proto.RegisterType((*StructifyMessageOptions)(nil), "structify.StructifyMessageOptions")
	proto.RegisterType((*StructifyFieldOptions)(nil), "structify.StructifyFieldOptions")
	proto.RegisterType((*Relation)(nil), "structify.Relation")
	proto.RegisterType((*MethodOptions)(nil), "structify.MethodOptions")
	proto.RegisterExtension(E_Db)
	proto.RegisterExtension(E_Opts)
	proto.RegisterExtension(E_Field)
	proto.RegisterExtension(E_Method)
}

func init() { proto.RegisterFile("plugin/options/structify.proto", fileDescriptor_e38015b89ec607b3) }

var fileDescriptor_e38015b89ec607b3 = []byte{
	// 539 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x93, 0xdb, 0x6a, 0xdb, 0x40,
	0x10, 0x86, 0xf1, 0x49, 0x96, 0x27, 0xa4, 0x94, 0xed, 0x21, 0x4b, 0x68, 0x1c, 0x23, 0x28, 0xe4,
	0x4a, 0x32, 0x29, 0x6d, 0xc1, 0xbd, 0x33, 0x6d, 0x20, 0x14, 0x53, 0x50, 0x0b, 0xa5, 0xed, 0x85,
	0xd1, 0x61, 0xec, 0x6c, 0xb2, 0xd6, 0xaa, 0xab, 0x5d, 0x53, 0xbd, 0x40, 0xe9, 0x43, 0xf4, 0xa9,
	0xfa, 0x14, 0x7d, 0x8c, 0xa0, 0xd5, 0xc1, 0x32, 0xf1, 0xdd, 0xce, 0xbf, 0x3f, 0x9f, 0xf6, 0x9f,
	0x19, 0xc1, 0x38, 0xe5, 0x7a, 0xcd, 0x12, 0x4f, 0xa4, 0x8a, 0x89, 0x24, 0xf3, 0x32, 0x25, 0x75,
	0xa4, 0xd8, 0x2a, 0x77, 0x53, 0x29, 0x94, 0x20, 0xa3, 0x46, 0x38, 0x9d, 0xac, 0x85, 0x58, 0x73,
	0xf4, 0xcc, 0x45, 0xa8, 0x57, 0x5e, 0x8c, 0x59, 0x24, 0x59, 0xaa, 0x84, 0x2c, 0xcd, 0xce, 0x0f,
	0x20, 0x9f, 0x6b, 0xfb, 0xfb, 0xf9, 0xa7, 0x12, 0x49, 0x4e, 0xc1, 0x4e, 0xa5, 0xd8, 0xb2, 0x18,
	0x25, 0xed, 0x4c, 0x3a, 0x17, 0x23, 0xbf, 0xa9, 0xc9, 0x63, 0xe8, 0x69, 0xc9, 0x69, 0xd7, 0xc8,
	0xc5, 0x91, 0x9c, 0xc0, 0x50, 0x4b, 0xbe, 0xc4, 0x64, 0x4b, 0x7b, 0x46, 0xb5, 0xb4, 0xe4, 0x1f,
	0x92, 0xad, 0x73, 0x0d, 0x27, 0x0d, 0x7c, 0x81, 0x59, 0x16, 0xac, 0xb1, 0xfe, 0xc2, 0x53, 0x18,
	0xa8, 0x20, 0xe4, 0x58, 0xe1, 0xcb, 0x82, 0x50, 0x18, 0x46, 0x62, 0xb3, 0xc1, 0x44, 0x55, 0xfc,
	0xba, 0x74, 0xfe, 0x76, 0xe1, 0x59, 0xc3, 0xba, 0x62, 0xc8, 0xe3, 0x9a, 0x74, 0x0e, 0x47, 0xa9,
	0x64, 0x9b, 0x40, 0xe6, 0xcb, 0x3b, 0xcc, 0x0d, 0xcf, 0xf6, 0xa1, 0x92, 0x3e, 0x62, 0x4e, 0x5e,
	0xc2, 0xa3, 0x40, 0x2b, 0xb1, 0x64, 0x49, 0x24, 0xb1, 0x61, 0xdb, 0xfe, 0x71, 0xa1, 0x5e, 0xd7,
	0x22, 0x79, 0x0e, 0x96, 0x4e, 0xd8, 0x4f, 0x8d, 0x26, 0x84, 0xed, 0x57, 0x15, 0x21, 0xd0, 0xd7,
	0x9a, 0xc5, 0xb4, 0x6f, 0x54, 0x73, 0x2e, 0x5e, 0xcf, 0x92, 0x18, 0x7f, 0xd1, 0x81, 0x11, 0xcb,
	0xa2, 0x70, 0x66, 0x77, 0x2c, 0xa5, 0x56, 0xe9, 0x2c, 0xce, 0x45, 0x27, 0x13, 0xcd, 0xb9, 0x89,
	0x3a, 0x34, 0x7a, 0x53, 0x17, 0x69, 0x63, 0x5c, 0x05, 0x9a, 0x2b, 0x6a, 0x97, 0x69, 0xab, 0x92,
	0x78, 0x60, 0x4b, 0xe4, 0x41, 0x11, 0x90, 0x8e, 0x26, 0x9d, 0x8b, 0xa3, 0xcb, 0x27, 0xee, 0x6e,
	0xcc, 0x7e, 0x75, 0xe5, 0x37, 0x26, 0x67, 0x0e, 0x76, 0xad, 0x16, 0x41, 0x56, 0x45, 0x83, 0x32,
	0xda, 0x99, 0xf4, 0x8a, 0x69, 0x94, 0x15, 0x19, 0x03, 0x48, 0x5c, 0xa1, 0xc4, 0x24, 0xc2, 0x8c,
	0x76, 0xcd, 0x5d, 0x4b, 0x71, 0xa6, 0x70, 0xbc, 0x40, 0x75, 0x23, 0xda, 0x9d, 0x15, 0xe1, 0x2d,
	0x46, 0x6a, 0xa9, 0xf2, 0xb4, 0x9e, 0x14, 0x94, 0xd2, 0x97, 0x3c, 0xc5, 0xd9, 0x02, 0xba, 0x71,
	0x48, 0x5e, 0xb8, 0xe5, 0x96, 0xb9, 0xf5, 0x96, 0xb9, 0x57, 0x8c, 0xd7, 0x83, 0xa6, 0xff, 0x7e,
	0xf7, 0x4c, 0x80, 0xb3, 0x56, 0x80, 0x87, 0x1b, 0xe7, 0x77, 0xe3, 0x70, 0xf6, 0x0d, 0xfa, 0x22,
	0x55, 0x19, 0x39, 0x7f, 0x00, 0xdc, 0x5f, 0x1e, 0xfa, 0xff, 0x8f, 0x65, 0x98, 0xce, 0x21, 0xe6,
	0xbe, 0xd7, 0x37, 0xc8, 0xd9, 0x57, 0x18, 0x98, 0x2e, 0x90, 0xb3, 0x03, 0x8f, 0xdd, 0x2d, 0x53,
	0x43, 0x9e, 0x1c, 0x22, 0xb7, 0x9d, 0x7e, 0xc9, 0x9b, 0xf9, 0x60, 0x6d, 0x4c, 0xd3, 0xc8, 0xf8,
	0xc0, 0xab, 0x5b, 0xdd, 0x6c, 0xd0, 0xb4, 0x85, 0xde, 0x73, 0xf8, 0x15, 0x69, 0xfe, 0xf6, 0xfb,
	0xeb, 0x35, 0x53, 0x37, 0x3a, 0x74, 0x23, 0xb1, 0xf1, 0xa2, 0xdb, 0xf4, 0xf2, 0xcd, 0x74, 0xba,
	0xfb, 0xcd, 0xbd, 0xfd, 0xff, 0xff, 0x5d, 0x73, 0x11, 0x5a, 0xe6, 0xd3, 0xaf, 0xee, 0x03, 0x00,
	0x00, 0xff, 0xff, 0x61, 0xce, 0x78, 0x34, 0x22, 0x04, 0x00, 0x00,
}
