// Code generated by protoc-gen-go. DO NOT EDIT.
// source: plugin/options/structify.proto

package structify

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StructifyDBOptions struct {
	Provider             string   `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Url                  string   `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	UrlEnv               string   `protobuf:"bytes,3,opt,name=url_env,json=urlEnv,proto3" json:"url_env,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StructifyDBOptions) Reset()         { *m = StructifyDBOptions{} }
func (m *StructifyDBOptions) String() string { return proto.CompactTextString(m) }
func (*StructifyDBOptions) ProtoMessage()    {}
func (*StructifyDBOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_e38015b89ec607b3, []int{0}
}

func (m *StructifyDBOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StructifyDBOptions.Unmarshal(m, b)
}
func (m *StructifyDBOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StructifyDBOptions.Marshal(b, m, deterministic)
}
func (m *StructifyDBOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StructifyDBOptions.Merge(m, src)
}
func (m *StructifyDBOptions) XXX_Size() int {
	return xxx_messageInfo_StructifyDBOptions.Size(m)
}
func (m *StructifyDBOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_StructifyDBOptions.DiscardUnknown(m)
}

var xxx_messageInfo_StructifyDBOptions proto.InternalMessageInfo

func (m *StructifyDBOptions) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

func (m *StructifyDBOptions) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *StructifyDBOptions) GetUrlEnv() string {
	if m != nil {
		return m.UrlEnv
	}
	return ""
}

type StructifyMessageOptions struct {
	Table                string   `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	Comment              string   `protobuf:"bytes,2,opt,name=comment,proto3" json:"comment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StructifyMessageOptions) Reset()         { *m = StructifyMessageOptions{} }
func (m *StructifyMessageOptions) String() string { return proto.CompactTextString(m) }
func (*StructifyMessageOptions) ProtoMessage()    {}
func (*StructifyMessageOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_e38015b89ec607b3, []int{1}
}

func (m *StructifyMessageOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StructifyMessageOptions.Unmarshal(m, b)
}
func (m *StructifyMessageOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StructifyMessageOptions.Marshal(b, m, deterministic)
}
func (m *StructifyMessageOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StructifyMessageOptions.Merge(m, src)
}
func (m *StructifyMessageOptions) XXX_Size() int {
	return xxx_messageInfo_StructifyMessageOptions.Size(m)
}
func (m *StructifyMessageOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_StructifyMessageOptions.DiscardUnknown(m)
}

var xxx_messageInfo_StructifyMessageOptions proto.InternalMessageInfo

func (m *StructifyMessageOptions) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

func (m *StructifyMessageOptions) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

type StructifyFieldOptions struct {
	Tag                  *StructifyTag `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *StructifyFieldOptions) Reset()         { *m = StructifyFieldOptions{} }
func (m *StructifyFieldOptions) String() string { return proto.CompactTextString(m) }
func (*StructifyFieldOptions) ProtoMessage()    {}
func (*StructifyFieldOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_e38015b89ec607b3, []int{2}
}

func (m *StructifyFieldOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StructifyFieldOptions.Unmarshal(m, b)
}
func (m *StructifyFieldOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StructifyFieldOptions.Marshal(b, m, deterministic)
}
func (m *StructifyFieldOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StructifyFieldOptions.Merge(m, src)
}
func (m *StructifyFieldOptions) XXX_Size() int {
	return xxx_messageInfo_StructifyFieldOptions.Size(m)
}
func (m *StructifyFieldOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_StructifyFieldOptions.DiscardUnknown(m)
}

var xxx_messageInfo_StructifyFieldOptions proto.InternalMessageInfo

func (m *StructifyFieldOptions) GetTag() *StructifyTag {
	if m != nil {
		return m.Tag
	}
	return nil
}

type StructifyTag struct {
	Skip                 bool     `protobuf:"varint,1,opt,name=skip,proto3" json:"skip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StructifyTag) Reset()         { *m = StructifyTag{} }
func (m *StructifyTag) String() string { return proto.CompactTextString(m) }
func (*StructifyTag) ProtoMessage()    {}
func (*StructifyTag) Descriptor() ([]byte, []int) {
	return fileDescriptor_e38015b89ec607b3, []int{3}
}

func (m *StructifyTag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StructifyTag.Unmarshal(m, b)
}
func (m *StructifyTag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StructifyTag.Marshal(b, m, deterministic)
}
func (m *StructifyTag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StructifyTag.Merge(m, src)
}
func (m *StructifyTag) XXX_Size() int {
	return xxx_messageInfo_StructifyTag.Size(m)
}
func (m *StructifyTag) XXX_DiscardUnknown() {
	xxx_messageInfo_StructifyTag.DiscardUnknown(m)
}

var xxx_messageInfo_StructifyTag proto.InternalMessageInfo

func (m *StructifyTag) GetSkip() bool {
	if m != nil {
		return m.Skip
	}
	return false
}

type MethodOptions struct {
	ObjectType           string   `protobuf:"bytes,1,opt,name=object_type,json=objectType,proto3" json:"object_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MethodOptions) Reset()         { *m = MethodOptions{} }
func (m *MethodOptions) String() string { return proto.CompactTextString(m) }
func (*MethodOptions) ProtoMessage()    {}
func (*MethodOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_e38015b89ec607b3, []int{4}
}

func (m *MethodOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MethodOptions.Unmarshal(m, b)
}
func (m *MethodOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MethodOptions.Marshal(b, m, deterministic)
}
func (m *MethodOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MethodOptions.Merge(m, src)
}
func (m *MethodOptions) XXX_Size() int {
	return xxx_messageInfo_MethodOptions.Size(m)
}
func (m *MethodOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_MethodOptions.DiscardUnknown(m)
}

var xxx_messageInfo_MethodOptions proto.InternalMessageInfo

func (m *MethodOptions) GetObjectType() string {
	if m != nil {
		return m.ObjectType
	}
	return ""
}

var E_Db = &proto.ExtensionDesc{
	ExtendedType:  (*descriptorpb.FileOptions)(nil),
	ExtensionType: (*StructifyDBOptions)(nil),
	Field:         50000,
	Name:          "structify.db",
	Tag:           "bytes,50000,opt,name=db",
	Filename:      "plugin/options/structify.proto",
}

var E_Opts = &proto.ExtensionDesc{
	ExtendedType:  (*descriptorpb.MessageOptions)(nil),
	ExtensionType: (*StructifyMessageOptions)(nil),
	Field:         99432,
	Name:          "structify.opts",
	Tag:           "bytes,99432,opt,name=opts",
	Filename:      "plugin/options/structify.proto",
}

var E_Field = &proto.ExtensionDesc{
	ExtendedType:  (*descriptorpb.FieldOptions)(nil),
	ExtensionType: (*StructifyFieldOptions)(nil),
	Field:         99432,
	Name:          "structify.field",
	Tag:           "bytes,99432,opt,name=field",
	Filename:      "plugin/options/structify.proto",
}

var E_Method = &proto.ExtensionDesc{
	ExtendedType:  (*descriptorpb.MethodOptions)(nil),
	ExtensionType: (*MethodOptions)(nil),
	Field:         99432,
	Name:          "structify.method",
	Tag:           "bytes,99432,opt,name=method",
	Filename:      "plugin/options/structify.proto",
}

func init() {
	proto.RegisterType((*StructifyDBOptions)(nil), "structify.StructifyDBOptions")
	proto.RegisterType((*StructifyMessageOptions)(nil), "structify.StructifyMessageOptions")
	proto.RegisterType((*StructifyFieldOptions)(nil), "structify.StructifyFieldOptions")
	proto.RegisterType((*StructifyTag)(nil), "structify.StructifyTag")
	proto.RegisterType((*MethodOptions)(nil), "structify.MethodOptions")
	proto.RegisterExtension(E_Db)
	proto.RegisterExtension(E_Opts)
	proto.RegisterExtension(E_Field)
	proto.RegisterExtension(E_Method)
}

func init() { proto.RegisterFile("plugin/options/structify.proto", fileDescriptor_e38015b89ec607b3) }

var fileDescriptor_e38015b89ec607b3 = []byte{
	// 414 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x93, 0xcf, 0xaa, 0xd3, 0x40,
	0x18, 0xc5, 0xb9, 0xcd, 0xbd, 0xb9, 0xb7, 0x5f, 0x15, 0x64, 0x50, 0x1a, 0x8a, 0xfd, 0x43, 0x56,
	0xba, 0x49, 0x4a, 0x45, 0x85, 0xb8, 0x2b, 0x5a, 0x70, 0x51, 0x84, 0xb1, 0x20, 0xea, 0xa2, 0xe4,
	0xcf, 0x34, 0x9d, 0x3a, 0xc9, 0x0c, 0x93, 0x49, 0xa1, 0x2f, 0x20, 0x3e, 0x9e, 0x8f, 0xe1, 0x63,
	0x48, 0x27, 0xcd, 0x34, 0xe1, 0x66, 0x37, 0xdf, 0x99, 0x93, 0xdf, 0x77, 0x72, 0x48, 0x60, 0x22,
	0x58, 0x99, 0xd2, 0xdc, 0xe7, 0x42, 0x51, 0x9e, 0x17, 0x7e, 0xa1, 0x64, 0x19, 0x2b, 0xba, 0x3b,
	0x79, 0x42, 0x72, 0xc5, 0x51, 0xdf, 0x08, 0xa3, 0x59, 0xca, 0x79, 0xca, 0x88, 0xaf, 0x2f, 0xa2,
	0x72, 0xe7, 0x27, 0xa4, 0x88, 0x25, 0x15, 0x8a, 0xcb, 0xca, 0xec, 0xfe, 0x04, 0xf4, 0xb5, 0xb6,
	0x7f, 0x5c, 0x7e, 0xa9, 0x90, 0x68, 0x04, 0x0f, 0x42, 0xf2, 0x23, 0x4d, 0x88, 0x74, 0x6e, 0x66,
	0x37, 0xaf, 0xfa, 0xd8, 0xcc, 0xe8, 0x19, 0x58, 0xa5, 0x64, 0x4e, 0x4f, 0xcb, 0xe7, 0x23, 0x1a,
	0xc2, 0x7d, 0x29, 0xd9, 0x96, 0xe4, 0x47, 0xc7, 0xd2, 0xaa, 0x5d, 0x4a, 0xf6, 0x29, 0x3f, 0xba,
	0x9f, 0x61, 0x68, 0xe0, 0x6b, 0x52, 0x14, 0x61, 0x4a, 0xea, 0x0d, 0xcf, 0xe1, 0x4e, 0x85, 0x11,
	0x23, 0x17, 0x7c, 0x35, 0x20, 0x07, 0xee, 0x63, 0x9e, 0x65, 0x24, 0x57, 0x17, 0x7e, 0x3d, 0xba,
	0x4b, 0x78, 0x61, 0x50, 0x2b, 0x4a, 0x58, 0x52, 0x83, 0x5e, 0x83, 0xa5, 0xc2, 0x54, 0x63, 0x06,
	0x8b, 0xa1, 0x77, 0x2d, 0xc3, 0xd8, 0x37, 0x61, 0x8a, 0xcf, 0x1e, 0xd7, 0x85, 0x27, 0x4d, 0x11,
	0x21, 0xb8, 0x2d, 0x7e, 0x51, 0xa1, 0x9f, 0x7d, 0xc0, 0xfa, 0xec, 0xce, 0xe1, 0xe9, 0x9a, 0xa8,
	0x3d, 0x37, 0xfc, 0x29, 0x0c, 0x78, 0x74, 0x20, 0xb1, 0xda, 0xaa, 0x93, 0xa8, 0xe3, 0x42, 0x25,
	0x6d, 0x4e, 0x82, 0x04, 0x6b, 0xe8, 0x25, 0x11, 0x7a, 0xe9, 0x55, 0x55, 0x7b, 0x75, 0xd5, 0xde,
	0x8a, 0xb2, 0xfa, 0x6d, 0x9d, 0xbf, 0xbf, 0x2d, 0x9d, 0x6f, 0xdc, 0x95, 0xcf, 0xd4, 0x8e, 0x7b,
	0x49, 0x14, 0x7c, 0x87, 0x5b, 0x2e, 0x54, 0x81, 0xa6, 0x8f, 0x80, 0xed, 0x06, 0x9d, 0x7f, 0x7f,
	0x6c, 0xcd, 0x74, 0xbb, 0x98, 0x6d, 0x2f, 0xd6, 0xc8, 0xe0, 0x1b, 0xdc, 0xed, 0xce, 0xd5, 0xa1,
	0x71, 0x47, 0xd8, 0x6b, 0xa5, 0x86, 0x3c, 0xeb, 0x22, 0x37, 0x9d, 0xb8, 0xe2, 0x05, 0x18, 0xec,
	0x4c, 0x97, 0x86, 0x26, 0x1d, 0xa9, 0x1b, 0x6d, 0x1a, 0xb4, 0xd3, 0x40, 0xb7, 0x1c, 0xf8, 0x42,
	0x5a, 0xbe, 0xff, 0xf1, 0x36, 0xa5, 0x6a, 0x5f, 0x46, 0x5e, 0xcc, 0x33, 0x3f, 0x3e, 0x88, 0xc5,
	0xbb, 0xf9, 0xfc, 0xfa, 0xad, 0xfb, 0xed, 0x9f, 0xe0, 0x83, 0xb9, 0x88, 0x6c, 0xbd, 0xfa, 0xcd,
	0xff, 0x00, 0x00, 0x00, 0xff, 0xff, 0x20, 0x67, 0x5e, 0xe8, 0x27, 0x03, 0x00, 0x00,
}
