// Code generated by protoc-gen-go. DO NOT EDIT.
// source: plugin/options/structify.proto

package structify

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// StructifyDBOptions defines the options for the database connection
type StructifyDBOptions struct {
	Provider             string   `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Url                  string   `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	UrlEnv               string   `protobuf:"bytes,3,opt,name=url_env,json=urlEnv,proto3" json:"url_env,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StructifyDBOptions) Reset()         { *m = StructifyDBOptions{} }
func (m *StructifyDBOptions) String() string { return proto.CompactTextString(m) }
func (*StructifyDBOptions) ProtoMessage()    {}
func (*StructifyDBOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_e38015b89ec607b3, []int{0}
}

func (m *StructifyDBOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StructifyDBOptions.Unmarshal(m, b)
}
func (m *StructifyDBOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StructifyDBOptions.Marshal(b, m, deterministic)
}
func (m *StructifyDBOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StructifyDBOptions.Merge(m, src)
}
func (m *StructifyDBOptions) XXX_Size() int {
	return xxx_messageInfo_StructifyDBOptions.Size(m)
}
func (m *StructifyDBOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_StructifyDBOptions.DiscardUnknown(m)
}

var xxx_messageInfo_StructifyDBOptions proto.InternalMessageInfo

func (m *StructifyDBOptions) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

func (m *StructifyDBOptions) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *StructifyDBOptions) GetUrlEnv() string {
	if m != nil {
		return m.UrlEnv
	}
	return ""
}

// StructifyMessageOptions defines database table and comment
type StructifyMessageOptions struct {
	Table                string   `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	Comment              string   `protobuf:"bytes,2,opt,name=comment,proto3" json:"comment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StructifyMessageOptions) Reset()         { *m = StructifyMessageOptions{} }
func (m *StructifyMessageOptions) String() string { return proto.CompactTextString(m) }
func (*StructifyMessageOptions) ProtoMessage()    {}
func (*StructifyMessageOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_e38015b89ec607b3, []int{1}
}

func (m *StructifyMessageOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StructifyMessageOptions.Unmarshal(m, b)
}
func (m *StructifyMessageOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StructifyMessageOptions.Marshal(b, m, deterministic)
}
func (m *StructifyMessageOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StructifyMessageOptions.Merge(m, src)
}
func (m *StructifyMessageOptions) XXX_Size() int {
	return xxx_messageInfo_StructifyMessageOptions.Size(m)
}
func (m *StructifyMessageOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_StructifyMessageOptions.DiscardUnknown(m)
}

var xxx_messageInfo_StructifyMessageOptions proto.InternalMessageInfo

func (m *StructifyMessageOptions) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

func (m *StructifyMessageOptions) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

// StructifyFieldOptions defines database field options
type StructifyFieldOptions struct {
	// primary_key defines the field as the primary key
	PrimaryKey bool `protobuf:"varint,1,opt,name=primary_key,json=primaryKey,proto3" json:"primary_key,omitempty"`
	// auto_increment defines the field as auto increment
	AutoIncrement bool `protobuf:"varint,2,opt,name=auto_increment,json=autoIncrement,proto3" json:"auto_increment,omitempty"`
	// unique defines the field as unique
	Unique bool `protobuf:"varint,3,opt,name=unique,proto3" json:"unique,omitempty"`
	// uuid defines the field as uuid
	Uuid bool `protobuf:"varint,4,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// index defines the field as index
	Index bool `protobuf:"varint,5,opt,name=index,proto3" json:"index,omitempty"`
	// skip defines the field as skip
	Skip bool `protobuf:"varint,6,opt,name=skip,proto3" json:"skip,omitempty"`
	// nullable defines the field as nullable
	Nullable bool `protobuf:"varint,7,opt,name=nullable,proto3" json:"nullable,omitempty"`
	// default defines the field as default
	Default string `protobuf:"bytes,8,opt,name=default,proto3" json:"default,omitempty"`
	// relation defines the field as relation
	// 1:1, 1:n, n:1, n:n
	Relation *Relation `protobuf:"bytes,9,opt,name=relation,proto3" json:"relation,omitempty"`
	// json defines the field as json
	Json                 bool     `protobuf:"varint,10,opt,name=json,proto3" json:"json,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StructifyFieldOptions) Reset()         { *m = StructifyFieldOptions{} }
func (m *StructifyFieldOptions) String() string { return proto.CompactTextString(m) }
func (*StructifyFieldOptions) ProtoMessage()    {}
func (*StructifyFieldOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_e38015b89ec607b3, []int{2}
}

func (m *StructifyFieldOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StructifyFieldOptions.Unmarshal(m, b)
}
func (m *StructifyFieldOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StructifyFieldOptions.Marshal(b, m, deterministic)
}
func (m *StructifyFieldOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StructifyFieldOptions.Merge(m, src)
}
func (m *StructifyFieldOptions) XXX_Size() int {
	return xxx_messageInfo_StructifyFieldOptions.Size(m)
}
func (m *StructifyFieldOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_StructifyFieldOptions.DiscardUnknown(m)
}

var xxx_messageInfo_StructifyFieldOptions proto.InternalMessageInfo

func (m *StructifyFieldOptions) GetPrimaryKey() bool {
	if m != nil {
		return m.PrimaryKey
	}
	return false
}

func (m *StructifyFieldOptions) GetAutoIncrement() bool {
	if m != nil {
		return m.AutoIncrement
	}
	return false
}

func (m *StructifyFieldOptions) GetUnique() bool {
	if m != nil {
		return m.Unique
	}
	return false
}

func (m *StructifyFieldOptions) GetUuid() bool {
	if m != nil {
		return m.Uuid
	}
	return false
}

func (m *StructifyFieldOptions) GetIndex() bool {
	if m != nil {
		return m.Index
	}
	return false
}

func (m *StructifyFieldOptions) GetSkip() bool {
	if m != nil {
		return m.Skip
	}
	return false
}

func (m *StructifyFieldOptions) GetNullable() bool {
	if m != nil {
		return m.Nullable
	}
	return false
}

func (m *StructifyFieldOptions) GetDefault() string {
	if m != nil {
		return m.Default
	}
	return ""
}

func (m *StructifyFieldOptions) GetRelation() *Relation {
	if m != nil {
		return m.Relation
	}
	return nil
}

func (m *StructifyFieldOptions) GetJson() bool {
	if m != nil {
		return m.Json
	}
	return false
}

// Relation defines the relation between two tables
type Relation struct {
	// field defines the field name
	Field string `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	// reference defines the reference table
	Reference            string   `protobuf:"bytes,2,opt,name=reference,proto3" json:"reference,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Relation) Reset()         { *m = Relation{} }
func (m *Relation) String() string { return proto.CompactTextString(m) }
func (*Relation) ProtoMessage()    {}
func (*Relation) Descriptor() ([]byte, []int) {
	return fileDescriptor_e38015b89ec607b3, []int{3}
}

func (m *Relation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Relation.Unmarshal(m, b)
}
func (m *Relation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Relation.Marshal(b, m, deterministic)
}
func (m *Relation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Relation.Merge(m, src)
}
func (m *Relation) XXX_Size() int {
	return xxx_messageInfo_Relation.Size(m)
}
func (m *Relation) XXX_DiscardUnknown() {
	xxx_messageInfo_Relation.DiscardUnknown(m)
}

var xxx_messageInfo_Relation proto.InternalMessageInfo

func (m *Relation) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

func (m *Relation) GetReference() string {
	if m != nil {
		return m.Reference
	}
	return ""
}

// MethodOptions defines the method options
type MethodOptions struct {
	ObjectType           string   `protobuf:"bytes,1,opt,name=object_type,json=objectType,proto3" json:"object_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MethodOptions) Reset()         { *m = MethodOptions{} }
func (m *MethodOptions) String() string { return proto.CompactTextString(m) }
func (*MethodOptions) ProtoMessage()    {}
func (*MethodOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_e38015b89ec607b3, []int{4}
}

func (m *MethodOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MethodOptions.Unmarshal(m, b)
}
func (m *MethodOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MethodOptions.Marshal(b, m, deterministic)
}
func (m *MethodOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MethodOptions.Merge(m, src)
}
func (m *MethodOptions) XXX_Size() int {
	return xxx_messageInfo_MethodOptions.Size(m)
}
func (m *MethodOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_MethodOptions.DiscardUnknown(m)
}

var xxx_messageInfo_MethodOptions proto.InternalMessageInfo

func (m *MethodOptions) GetObjectType() string {
	if m != nil {
		return m.ObjectType
	}
	return ""
}

var E_Db = &proto.ExtensionDesc{
	ExtendedType:  (*descriptorpb.FileOptions)(nil),
	ExtensionType: (*StructifyDBOptions)(nil),
	Field:         50002,
	Name:          "structify.db",
	Tag:           "bytes,50002,opt,name=db",
	Filename:      "plugin/options/structify.proto",
}

var E_Opts = &proto.ExtensionDesc{
	ExtendedType:  (*descriptorpb.MessageOptions)(nil),
	ExtensionType: (*StructifyMessageOptions)(nil),
	Field:         99432,
	Name:          "structify.opts",
	Tag:           "bytes,99432,opt,name=opts",
	Filename:      "plugin/options/structify.proto",
}

var E_Field = &proto.ExtensionDesc{
	ExtendedType:  (*descriptorpb.FieldOptions)(nil),
	ExtensionType: (*StructifyFieldOptions)(nil),
	Field:         99432,
	Name:          "structify.field",
	Tag:           "bytes,99432,opt,name=field",
	Filename:      "plugin/options/structify.proto",
}

var E_Method = &proto.ExtensionDesc{
	ExtendedType:  (*descriptorpb.MethodOptions)(nil),
	ExtensionType: (*MethodOptions)(nil),
	Field:         99432,
	Name:          "structify.method",
	Tag:           "bytes,99432,opt,name=method",
	Filename:      "plugin/options/structify.proto",
}

func init() {
	proto.RegisterType((*StructifyDBOptions)(nil), "structify.StructifyDBOptions")
	proto.RegisterType((*StructifyMessageOptions)(nil), "structify.StructifyMessageOptions")
	proto.RegisterType((*StructifyFieldOptions)(nil), "structify.StructifyFieldOptions")
	proto.RegisterType((*Relation)(nil), "structify.Relation")
	proto.RegisterType((*MethodOptions)(nil), "structify.MethodOptions")
	proto.RegisterExtension(E_Db)
	proto.RegisterExtension(E_Opts)
	proto.RegisterExtension(E_Field)
	proto.RegisterExtension(E_Method)
}

func init() { proto.RegisterFile("plugin/options/structify.proto", fileDescriptor_e38015b89ec607b3) }

var fileDescriptor_e38015b89ec607b3 = []byte{
	// 545 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x94, 0xdb, 0x6a, 0x1b, 0x3d,
	0x14, 0x85, 0xf1, 0x21, 0xe3, 0xf1, 0x0e, 0xf9, 0xf9, 0x51, 0x0f, 0x11, 0x21, 0x07, 0x33, 0x50,
	0xc8, 0xd5, 0x8c, 0x49, 0x69, 0x0b, 0x2e, 0xf4, 0x22, 0xb4, 0x81, 0x50, 0x4c, 0x61, 0x5a, 0x28,
	0x6d, 0x2f, 0xcc, 0x1c, 0xb6, 0x1d, 0x39, 0xf2, 0x68, 0xaa, 0x91, 0x4c, 0xe7, 0x05, 0x4a, 0x1f,
	0xa7, 0xcf, 0xd2, 0xa7, 0xe8, 0x63, 0x14, 0x69, 0x0e, 0xb6, 0x89, 0xef, 0xb4, 0x97, 0x16, 0x9f,
	0xb4, 0x97, 0xf6, 0x0c, 0x9c, 0xe7, 0x5c, 0x2f, 0x58, 0x16, 0x88, 0x5c, 0x31, 0x91, 0x15, 0x41,
	0xa1, 0xa4, 0x4e, 0x14, 0x9b, 0x97, 0x7e, 0x2e, 0x85, 0x12, 0x64, 0xd8, 0x0a, 0x27, 0xa3, 0x85,
	0x10, 0x0b, 0x8e, 0x81, 0xdd, 0x88, 0xf5, 0x3c, 0x48, 0xb1, 0x48, 0x24, 0xcb, 0x95, 0x90, 0x95,
	0xd9, 0xfb, 0x06, 0xe4, 0x63, 0x63, 0x7f, 0x7b, 0xfd, 0xa1, 0x42, 0x92, 0x13, 0x70, 0x73, 0x29,
	0xd6, 0x2c, 0x45, 0x49, 0x3b, 0xa3, 0xce, 0xe5, 0x30, 0x6c, 0x6b, 0xf2, 0x3f, 0xf4, 0xb4, 0xe4,
	0xb4, 0x6b, 0x65, 0xb3, 0x24, 0xc7, 0x30, 0xd0, 0x92, 0xcf, 0x30, 0x5b, 0xd3, 0x9e, 0x55, 0x1d,
	0x2d, 0xf9, 0xbb, 0x6c, 0xed, 0xdd, 0xc2, 0x71, 0x0b, 0x9f, 0x62, 0x51, 0x44, 0x0b, 0x6c, 0x4e,
	0x78, 0x0c, 0x07, 0x2a, 0x8a, 0x39, 0xd6, 0xf8, 0xaa, 0x20, 0x14, 0x06, 0x89, 0x58, 0xad, 0x30,
	0x53, 0x35, 0xbf, 0x29, 0xbd, 0xdf, 0x5d, 0x78, 0xd2, 0xb2, 0x6e, 0x18, 0xf2, 0xb4, 0x21, 0x5d,
	0xc0, 0x61, 0x2e, 0xd9, 0x2a, 0x92, 0xe5, 0xec, 0x1e, 0x4b, 0xcb, 0x73, 0x43, 0xa8, 0xa5, 0xf7,
	0x58, 0x92, 0x67, 0xf0, 0x5f, 0xa4, 0x95, 0x98, 0xb1, 0x2c, 0x91, 0xd8, 0xb2, 0xdd, 0xf0, 0xc8,
	0xa8, 0xb7, 0x8d, 0x48, 0x9e, 0x82, 0xa3, 0x33, 0xf6, 0x5d, 0xa3, 0x6d, 0xc2, 0x0d, 0xeb, 0x8a,
	0x10, 0xe8, 0x6b, 0xcd, 0x52, 0xda, 0xb7, 0xaa, 0x5d, 0x9b, 0xdb, 0xb3, 0x2c, 0xc5, 0x1f, 0xf4,
	0xc0, 0x8a, 0x55, 0x61, 0x9c, 0xc5, 0x3d, 0xcb, 0xa9, 0x53, 0x39, 0xcd, 0xda, 0x24, 0x99, 0x69,
	0xce, 0x6d, 0xab, 0x03, 0xab, 0xb7, 0xb5, 0xe9, 0x36, 0xc5, 0x79, 0xa4, 0xb9, 0xa2, 0x6e, 0xd5,
	0x6d, 0x5d, 0x92, 0x00, 0x5c, 0x89, 0x3c, 0x32, 0x0d, 0xd2, 0xe1, 0xa8, 0x73, 0x79, 0x78, 0xf5,
	0xc8, 0xdf, 0x3c, 0x73, 0x58, 0x6f, 0x85, 0xad, 0xc9, 0x1c, 0xbd, 0x2c, 0x44, 0x46, 0xa1, 0x3a,
	0xda, 0xac, 0xbd, 0x37, 0xe0, 0x36, 0x4e, 0x73, 0xe1, 0xb9, 0x09, 0xad, 0x89, 0xdb, 0x16, 0xe4,
	0x14, 0x86, 0x12, 0xe7, 0x28, 0x31, 0x4b, 0xb0, 0x0e, 0x7c, 0x23, 0x78, 0x63, 0x38, 0x9a, 0xa2,
	0xba, 0x13, 0xdb, 0x49, 0x8b, 0x78, 0x89, 0x89, 0x9a, 0xa9, 0x32, 0x6f, 0x5e, 0x0e, 0x2a, 0xe9,
	0x53, 0x99, 0xe3, 0x64, 0x0a, 0xdd, 0x34, 0x26, 0xa7, 0x7e, 0x35, 0x75, 0x7e, 0x33, 0x75, 0xfe,
	0x0d, 0xe3, 0xcd, 0xc3, 0xd3, 0x3f, 0x3f, 0x7b, 0xb6, 0xa1, 0xb3, 0xad, 0x86, 0x1e, 0x4e, 0x60,
	0xd8, 0x4d, 0xe3, 0xc9, 0x17, 0xe8, 0x8b, 0x5c, 0x15, 0xe4, 0xe2, 0x01, 0x70, 0x77, 0x98, 0xe8,
	0xdf, 0x5f, 0x8e, 0x65, 0x7a, 0xfb, 0x98, 0xbb, 0xde, 0xd0, 0x22, 0x27, 0x9f, 0xeb, 0x3c, 0xc8,
	0xd9, 0x9e, 0xcb, 0x6e, 0x86, 0xab, 0x25, 0x8f, 0xf6, 0x91, 0xb7, 0x9d, 0x75, 0xa4, 0x93, 0x10,
	0x9c, 0x95, 0x0d, 0x8d, 0x9c, 0xef, 0xb9, 0xf5, 0x56, 0x9a, 0x2d, 0x9a, 0x6e, 0xa1, 0x77, 0x1c,
	0x61, 0x4d, 0xba, 0x7e, 0xf5, 0xf5, 0xc5, 0x82, 0xa9, 0x3b, 0x1d, 0xfb, 0x89, 0x58, 0x05, 0xc9,
	0x32, 0xbf, 0x7a, 0x39, 0x1e, 0x6f, 0x3e, 0xfb, 0x60, 0xf7, 0x7f, 0xf0, 0xba, 0xdd, 0x88, 0x1d,
	0x7b, 0xf4, 0xf3, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xe1, 0xd1, 0x42, 0x6d, 0x32, 0x04, 0x00,
	0x00,
}
